card_image: ''
created_at: 2025-04-15 13:50:02.722000
creator_id: unknown
deployment:
  last_deployed: null
  type: null
  url: ''
description: Android starter template
domain: ''
features:
- ''
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: https://github.com/memextech/android-template
hero_image: https://raw.githubusercontent.com/memextech/android-template/main/public/images/hero-image.png
icon: ''
is_published: true
pills:
- icon: Rocket
  label: Create 2D Game
  prompt: Create a 2D game using the Android template
project_id: BZuxnXzdoLbNtZQhApya
published_at: 2025-04-15 13:55:41.545000
requirements:
- description: ''
  type: ''
slug: ''
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: Android Starter Template
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-04-15 15:00:17.693000
